name = "zai-telegram-bot-bot"
compatibility_date = "2025-08-06"
main = "worker.js"

[vars]
TELEGRAM_BOT_TOKEN = "8285384768:AAGXNkTZfGm4OqyDqPEV3AQR9brWC0U2GNo"
ZAI_API_KEY = "93bf2ce436a144bb8f14061458cef55b.waBULwb6TvCHymvy"
