name = "terabox-bot"
compatibility_date = "2025-08-06"
main = "worker.js"

[vars]
TELEGRAM_BOT_TOKEN = "6559421973:AAFKDg5Ah7xPafoEqX-9QWN_7g2G7OTbGtc"
ZAI_API_KEY = "93bf2ce436a144bb8f14061458cef55b.waBULwb6TvCHymvy"
